// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/stepseq#s8n8

extern const LV2_Descriptor* lv2_descriptor(uint32_t index);
extern const LV2UI_Descriptor* lv2ui_descriptor(uint32_t index);

static const RtkLv2Description _plugin = {
	&lv2_descriptor,
	&lv2ui_descriptor
	, 0 // uint32_t dsp_descriptor_id
	, 0 // uint32_t gui_descriptor_id
	, "MIDI Step Sequencer8x8" // const char *plugin_human_id
	, (const struct LV2Port[82])
	{
		{ "control", ATOM_IN, nan, nan, nan, "Control Input"},
		{ "midiout", MIDI_OUT, nan, nan, nan, "MIDI Out"},
		{ "sync", CONTROL_IN, 0.000000, 0.000000, 1.000000, "Sync"},
		{ "bpm", CONTROL_IN, 120.000000, 40.000000, 208.000000, "BPM"},
		{ "div", CONTROL_IN, 3.000000, 0.000000, 9.000000, "Step Duration (4/4)"},
		{ "swing", CONTROL_IN, 0.000000, 0.000000, 0.500000, "Swing"},
		{ "drummode", CONTROL_IN, 0.000000, 0.000000, 1.000000, "Drum Mode"},
		{ "chn", CONTROL_IN, 0.000000, 0.000000, 15.000000, "Midi Channel"},
		{ "panic", CONTROL_IN, 0.000000, 0.000000, 1.000000, "MIDI Panic"},
		{ "pos", CONTROL_OUT, nan, 1.000000, 8.000000, "Step Position"},
		{ "note1", CONTROL_IN, 69.000000, 0.000000, 127.000000, "Note 1"},
		{ "note2", CONTROL_IN, 67.000000, 0.000000, 127.000000, "Note 2"},
		{ "note3", CONTROL_IN, 65.000000, 0.000000, 127.000000, "Note 3"},
		{ "note4", CONTROL_IN, 64.000000, 0.000000, 127.000000, "Note 4"},
		{ "note5", CONTROL_IN, 62.000000, 0.000000, 127.000000, "Note 5"},
		{ "note6", CONTROL_IN, 60.000000, 0.000000, 127.000000, "Note 6"},
		{ "note7", CONTROL_IN, 59.000000, 0.000000, 127.000000, "Note 7"},
		{ "note8", CONTROL_IN, 57.000000, 0.000000, 127.000000, "Note 8"},
		{ "grid_1_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 1"},
		{ "grid_2_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 1"},
		{ "grid_3_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 1"},
		{ "grid_4_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 1"},
		{ "grid_5_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 1"},
		{ "grid_6_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 1"},
		{ "grid_7_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 1"},
		{ "grid_8_1", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 1"},
		{ "grid_1_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 2"},
		{ "grid_2_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 2"},
		{ "grid_3_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 2"},
		{ "grid_4_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 2"},
		{ "grid_5_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 2"},
		{ "grid_6_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 2"},
		{ "grid_7_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 2"},
		{ "grid_8_2", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 2"},
		{ "grid_1_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 3"},
		{ "grid_2_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 3"},
		{ "grid_3_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 3"},
		{ "grid_4_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 3"},
		{ "grid_5_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 3"},
		{ "grid_6_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 3"},
		{ "grid_7_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 3"},
		{ "grid_8_3", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 3"},
		{ "grid_1_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 4"},
		{ "grid_2_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 4"},
		{ "grid_3_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 4"},
		{ "grid_4_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 4"},
		{ "grid_5_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 4"},
		{ "grid_6_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 4"},
		{ "grid_7_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 4"},
		{ "grid_8_4", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 4"},
		{ "grid_1_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 5"},
		{ "grid_2_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 5"},
		{ "grid_3_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 5"},
		{ "grid_4_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 5"},
		{ "grid_5_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 5"},
		{ "grid_6_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 5"},
		{ "grid_7_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 5"},
		{ "grid_8_5", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 5"},
		{ "grid_1_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 6"},
		{ "grid_2_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 6"},
		{ "grid_3_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 6"},
		{ "grid_4_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 6"},
		{ "grid_5_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 6"},
		{ "grid_6_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 6"},
		{ "grid_7_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 6"},
		{ "grid_8_6", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 6"},
		{ "grid_1_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 7"},
		{ "grid_2_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 7"},
		{ "grid_3_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 7"},
		{ "grid_4_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 7"},
		{ "grid_5_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 7"},
		{ "grid_6_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 7"},
		{ "grid_7_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 7"},
		{ "grid_8_7", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 7"},
		{ "grid_1_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 1 N: 8"},
		{ "grid_2_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 2 N: 8"},
		{ "grid_3_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 3 N: 8"},
		{ "grid_4_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 4 N: 8"},
		{ "grid_5_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 5 N: 8"},
		{ "grid_6_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 6 N: 8"},
		{ "grid_7_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 7 N: 8"},
		{ "grid_8_8", CONTROL_IN, 0.000000, 0.000000, 127.000000, "Grid S: 8 N: 8"},
	}
	, 82 // uint32_t nports_total
	, 0 // uint32_t nports_audio_in
	, 0 // uint32_t nports_audio_out
	, 0 // uint32_t nports_midi_in
	, 1 // uint32_t nports_midi_out
	, 1 // uint32_t nports_atom_in
	, 0 // uint32_t nports_atom_out
	, 80 // uint32_t nports_ctrl
	, 79 // uint32_t nports_ctrl_in
	, 1 // uint32_t nports_ctrl_out
	, 8192 // uint32_t min_atom_bufsiz
	, true // bool send_time_info
	, UINT32_MAX // uint32_t latency_ctrl_port
};
